version: "3.1"

services:
  database:
    image: mysql
    container_name: mysql-database
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD?Incorrect database password}
      MYSQL_DATABASE: Bittersweet
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql